apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: s4lvious/carrot-backend:latest
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql:3306/carrotpmi"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: WEBHOOK_TOKEN
          value: Bearer qwertyuiopASDFGHJKL1234567890abcXYZ
        - name: FATTURA_API_URL
          value: https://fattura-elettronica-api.it/ws2.0/test/fatture
        - name: FATTURA_API_AUTH
          value: Basic cy5saWNjYXJkbzAyMkBnbWFpbC5jb206eFUzN21MbHJ4Zw==
        - name: gocardless_bad_secret-id
          value: 5106d36f-2fee-4c83-bbba-612043c07f24
        - name: gocardless_bad_secret-key
          value: 19f3084a9c938508951663046bac296bd84d42c15edb2033d5239f0295e412ee8221c1545d9c51eedd83a580723cdbe3232b5001d2b4d997a8a61ebfc638b44c
        - name: gocardless_bad_api-url
          value: https://bankaccountdata.gocardless.com/api/v2


        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080        # Porta del Service esposta nel cluster
      targetPort: 8080  # Deve essere uguale alla porta del container
  type: ClusterIP  # Default, accessibile solo dentro il cluster