apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: s4lvious/carrot-backend:latest
        env:
        - name: DB_URL
          value: "jdbc:mysql://mysql:3306/carrotpmi"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
            ephemeral-storage: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080        # Porta del Service esposta nel cluster
      targetPort: 8080  # Deve essere uguale alla porta del container
  type: ClusterIP  # Default, accessibile solo dentro il cluster